import Layout from '../component/Layout';
import Head from 'next/head';
import Image from 'next/image';
import styles from './About.module.css';
import photo from '../public/photo.svg';
import skills from '../public/skills.svg';
import music from '../public/music.svg';
import camera from '../public/camera.svg';
import travel from '../public/travel.svg';
import ciak from '../public/ciak.svg';

const about = () => {
  return (
    <>
      <Head>
        <title>Lisa Borrelli - About Me</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <div className={styles.aboutContainer}>
          <div className={styles.aboutContainerChild}>
            <h1>
              Ciao,
              <br />I am Lisa
            </h1>
            <div className={styles.dots}>
              <span />
              <span />
              <span />
              <span />
              <span />
              <span />
              <span />
              <span />
            </div>
            <h4>
              I’m a Graphic & Digital Designer <br />
              based in London
            </h4>
            <p>
              My aim is to use my variety of skills to help businesses grow with
              visual impactful design.{' '}
            </p>
          </div>
          <div className={styles.aboutContainerChild}>
            <Image src={photo} />
          </div>
        </div>
        <div className={styles.aboutContainer}>
          <h1>My Skills</h1>
          <div className={styles.dots}>
            <span />
            <span />
            <span />
            <span />
            <span />
            <span />
            <span />
            <span />
          </div>
          <div className={styles.skills}>
            <div>
              UI DESIGN
              <span className={`${styles.skill} ${styles.uiDesign}`}></span>
            </div>
            <div>
              BRANDING
              <span className={`${styles.skill} ${styles.branding}`}></span>
            </div>
            <div>
              WORDPRESS
              <span className={`${styles.skill} ${styles.wordpress}`}></span>
            </div>
            <div>
              PHOTOGRAPHY
              <span className={`${styles.skill} ${styles.photography}`}></span>
            </div>
            <div>
              MAILCHIMP
              <span className={`${styles.skill} ${styles.mailchimp}`}></span>
            </div>
            <div>
              INFOGRAPHIC
              <span className={`${styles.skill} ${styles.infographic}`}></span>
            </div>
          </div>
          <Image src={skills} />
        </div>
        <div className={styles.aboutContainer}>
          <h1>A little more about me</h1>
          <div className={styles.dots}>
            <span />
            <span />
            <span />
            <span />
            <span />
            <span />
            <span />
            <span />
          </div>
          <div className={styles.icons}>
            <Image src={travel} />
            <Image src={music} />
            <Image src={camera} />
            <Image src={ciak} />
          </div>
        </div>
      </Layout>
    </>
  );
};

export default about;
