// import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Layout from '../component/Layout';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Purus sit amet luctus venenatis lectus. Sit amet purus gravida quis blandit turpis cursus in hac. In eu mi bibendum neque egestas congue quisque egestas. Aenean sed adipiscing diam donec adipiscing tristique risus nec. Urna neque viverra justo nec ultrices. In hendrerit gravida rutrum quisque non tellus orci. Urna neque viverra justo nec ultrices dui sapien eget. Adipiscing elit ut aliquam purus sit amet luctus. Arcu cursus euismod quis viverra nibh. Nisi est sit amet facilisis magna etiam tempor orci eu. Ultricies mi quis hendrerit dolor. Feugiat nisl pretium fusce id. Eget nulla facilisi etiam dignissim diam quis enim.

Tempus iaculis urna id volutpat lacus laoreet. Commodo odio aenean sed adipiscing diam donec. In egestas erat imperdiet sed euismod nisi porta lorem mollis. Enim tortor at auctor urna nunc id. Ut ornare lectus sit amet. Ut venenatis tellus in metus vulputate eu scelerisque felis imperdiet. Libero nunc consequat interdum varius. Turpis nunc eget lorem dolor sed viverra. Tortor vitae purus faucibus ornare. Eget arcu dictum varius duis at consectetur lorem donec. In metus vulputate eu scelerisque felis.

Tristique magna sit amet purus. Convallis tellus id interdum velit laoreet. Fermentum odio eu feugiat pretium nibh ipsum consequat nisl. Nibh nisl condimentum id venenatis a condimentum vitae sapien pellentesque. Velit egestas dui id ornare arcu odio ut. Lectus arcu bibendum at varius vel pharetra vel. At quis risus sed vulputate odio. Neque laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt. Dignissim suspendisse in est ante in. Et leo duis ut diam quam nulla porttitor massa id. Sagittis orci a scelerisque purus semper eget duis at tellus. Tristique et egestas quis ipsum suspendisse ultrices. Orci nulla pellentesque dignissim enim sit amet venenatis urna cursus. Sit amet consectetur adipiscing elit ut aliquam purus sit. Ut tellus elementum sagittis vitae. Tempor commodo ullamcorper a lacus vestibulum sed. Non consectetur a erat nam.</Layout>
    </>
  );
}
