import Image from 'next/image';
import Layout from '../component/Layout';
import Head from 'next/head';
import { createClient } from 'contentful';

export async function getStaticProps() {
  const client = createClient({
    space: process.env.CONTENTFUL_SPACE_ID,
    accessToken: process.env.CONTENTFUL_ACCESS_KEY,
  });
  const response = await client.getEntries({ content_type: 'project' });
  return {
    props: {
      projects: response.items,
    },
  };
}

export async function getStaticPaths(){
  
}

export default function Home({ projects }) {
  // console.log(projects);
  // console.log(projects[0].fields.mainImage.fields.file.url);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        {projects.map((project) => {
          return (
            <div key={project.sys.id} className='image'>
              {/* <Image
                src={`https:${project.fields.mainImage.fields.file.url}`}
                width={800}
                height={450}
                layout='fill'
                objectFit='cover'
              /> */}
              <img
                className='main-img'
                src={`https:${project.fields.mainImage.fields.file.url}`}
              />
            </div>
          );
        })}
        {/* <Image src={`https:${projects[0].fields.mainImage.fields.file.url}`} layout='fill'/> */}
      </Layout>
    </>
  );
}
